### ISSUE TITLE
Don't validate none virtual properties

### ISSUE THREAD

**Issue by Drol** [madsstorm/CodeAnalyzers.Episerver#2]
Epi2014, Epi2015 and Epi2016 should not trigger validation on none virtual properties. Example:

`public ContentReference Test { get; set; }`

I know it is a edge case but we sometimes use something like `public ContentReference SearchReferencingContent => this.GetReferencingContent();` where GetReferencingContent() is a fetching some data for Find to index.

**Comment by madsstorm** [comment]
Solved in version 1.2.1
